apiVersion: apps/v1
kind: Deployment
metadata:
  name: audio-summarizer-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: audio-summarizer-app
  template:
    metadata:
      labels:
        app: audio-summarizer-app
    spec:
      containers:
      - name: audio-summarizer-app
        image: <acrName>.azurecr.io/audio-summarizer/app:v1
        ports:
        - containerPort: 8081
