version: '3.8'

services:
  api:
    container_name: BookSummarizer-api
    image: generalregistry.azurecr.io/booksummarizer_api
    build:
      context: ../api
      dockerfile: Dockerfile
    ports:
      - "5555:5555"
    restart: always

  ui:
    container_name: BookSummarizer-ui
    image: generalregistry.azurecr.io/booksummarizer_ui
    build:
      context: ../UI
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    restart: always
