apiVersion: apps/v1
kind: Deployment
metadata:
  name: audio-summarizer-ui
spec:
  replicas: 3
  selector:
    matchLabels:
      app: audio-summarizer-ui
  template:
    metadata:
      labels:
        app: audio-summarizer-ui
    spec:
      containers:
      - name: audio-summarizer-ui
        image: <acrName>.azurecr.io/audio-summarizer/ui:v1
        ports:
        - containerPort: 80
